Remove pymoab as a Dependency
svalinn/pydagmc pull request #24
Opened 2024-05-24 17:46 UTC by ahnaf-tahmid-chowdhury

## Description

This PR removes `pymoab` from `pyproject.toml` as a dependency.

## Changes

Here are the main changes made in this PR:

1. **`pyproject.toml`:** Removed `pymoab` from the list of dependencies.

2. **`dagnav.py`:** Added instructions to handle the case if `pymoab` is not found.

2024-05-28 22:42 UTC, pshriwise commented on dagmc/dagnav.py
> +access, manipulation, and storage of geometric data.
```suggestion
modeling and simulation built upon the PyMOAB package.
```

2024-05-28 22:51 UTC, pshriwise commented on dagmc/dagnav.py
> +except ImportError as e:
I know I suggested this in #1, but the message is a overly verbose for my taste. There are (somewhat dated) instructions on how to build MOAB with PyMOAB enabled [here](https://ftp.mcs.anl.gov/pub/fathom/moab-docs/building.html). I think we should point to them in this message and update the installation instructions there.

Also, while we may want to add a logging capability to this project in the future, I don't see the point of importing that module for this single message. We can raise our own message from a `ModuleNotFoundError` 

```python

try:
    from pymoab import core, types, rng, tag
except ImportError as e:
    msg = 'PyMOAB package was not found, please install this package using the instructions found here: https://ftp.mcs.anl.gov/pub/fathom/moab-docs/building.html'
    raise ModuleNotFoundError(msg) from e
```

2024-05-28 22:51 UTC, pshriwise requested changes
A couple of comments form me, but I think this is close!

2024-05-30 14:32 UTC, gonuke approved these changes
LGTM - I'll let @pshriwise decide if it's ready

2024-05-30 15:28 UTC, pshriwise approved these changes

2024-05-30 15:28 UTC, merged